#!/bin/bash
cd pdf.js
# TEMP: Use --force because of https://github.com/mozilla/pdf.js/issues/15429#issuecomment-1278856773
npm ci --force
npx gulp lib
cd ..
mkdir -p build/cmaps
rsync -av --recursive --exclude='.*' pdf.js/external/bcmaps/ build/cmaps/
rsync -av --recursive --exclude='.*'  pdf.js/external/standard_fonts/ build/standard_fonts/
